seed: 42

objective: pointwise

dataloader:
  split_ratio:
    trn: 8
    val: 1
    tst: 1
  num_negatives:
    opt: 4
    eval: 99
  batch_size: 256

histories:
  selector: default
  max_hist: 

trainer:
  criterion: bce

optimizer:
  name: adam
  lr: 1e-4
  weight_decay: 1e-6

monitor:
  criterion: ndcg
  delta: 1e-3
  patience: 5
  warmup: 10

runner:
  num_epochs: 1000

evaluator:
  k_list: [5, 10, 15, 20, 25, 50, 100]